apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: infrastructure-operator
  name: assisted-installer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: infrastructure-operator
  namespace: assisted-installer
  labels:
    control-plane: infrastructure-operator
spec:
  selector:
    matchLabels:
      control-plane: infrastructure-operator
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: infrastructure-operator
    spec:
      containers:
      - command:
        - /assisted-service-operator
        args:
        - --leader-elect
        image: quay.io/edge-infrastructure/assisted-service:ocm-2.4
        name: manager
        env:
          - name: SERVICE_IMAGE
            value: quay.io/edge-infrastructure/assisted-service:ocm-2.4
          - name: IMAGE_SERVICE_IMAGE
            value: quay.io/edge-infrastructure/assisted-image-service:ocm-2.4
          - name: DATABASE_IMAGE
            value: quay.io/edge-infrastructure/postgresql-12-centos7:latest
          - name: AGENT_IMAGE
            value: quay.io/edge-infrastructure/assisted-installer-agent:ocm-2.4
          - name: CONTROLLER_IMAGE
            value: quay.io/edge-infrastructure/assisted-installer-controller:ocm-2.4
          - name: INSTALLER_IMAGE
            value: quay.io/edge-infrastructure/assisted-installer:ocm-2.4
          - name: OPENSHIFT_VERSIONS
            value: '{"4.8":{"display_name":"4.8.10","release_version":"4.8.10","release_image":"quay.io/openshift-release-dev/ocp-release:4.8.10-x86_64","rhcos_image":"https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.8/4.8.2/rhcos-4.8.2-x86_64-live.x86_64.iso","rhcos_rootfs":"https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.8/4.8.2/rhcos-live-rootfs.x86_64.img","rhcos_version":"48.84.202107202156-0","support_level":"production","default":true},"4.9":{"display_name":"4.9.0","release_version":"4.9.0","release_image":"quay.io/openshift-release-dev/ocp-release:4.9.0-x86_64","rhcos_image":"https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.9/4.9.0/rhcos-4.9.0-x86_64-live.x86_64.iso","rhcos_rootfs":"https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.9/4.9.0/rhcos-live-rootfs.x86_64.img","rhcos_version":"49.84.202110081407-0","support_level":"production"}}' # openshift version
          - name: OS_IMAGES
            value: '[{"openshift_version":"4.8","cpu_architecture":"x86_64","url":"https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.8/4.8.2/rhcos-4.8.2-x86_64-live.x86_64.iso","rootfs_url":"https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.8/4.8.2/rhcos-live-rootfs.x86_64.img","version":"48.84.202107202156-0"},{"openshift_version":"4.9","cpu_architecture":"x86_64","url":"https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.9/4.9.0/rhcos-4.9.0-x86_64-live.x86_64.iso","rootfs_url":"https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.9/4.9.0/rhcos-live-rootfs.x86_64.img","version":"49.84.202110081407-0"}]' # os images
          - name: SERVICE_ACCOUNT_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.serviceAccountName
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        securityContext:
          allowPrivilegeEscalation: false
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
      serviceAccountName: assisted-service
      terminationGracePeriodSeconds: 10
