apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: bm-inventory
spec:
  selector:
    matchLabels:
      app: bm-inventory
  replicas: 1
  template:
    metadata:
      labels:
        app: bm-inventory
    spec:
      containers:
        - name: bm-inventory
          image: quay.io/mfilanov/bm-inventory
          imagePullPolicy: Always
          ports:
            - containerPort: 8090
          envFrom:
            - configMapRef:
                name: s3-config
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: bm-inventory
  name: bm-inventory
spec:
  ports:
    - port: 8090
      protocol: TCP
      targetPort: 8090
  selector:
    app: bm-inventory
  type: LoadBalancer
status:
  loadBalancer: {}
